name: Deploy Swagger to GitHub Pages

on:
  push:
    branches: [ feature/新增Swagger頁面 ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Install Swashbuckle CLI
      run: dotnet tool install -g Swashbuckle.AspNetCore.Cli
    - name: Build
      run: dotnet build src/FrontStage/FrontStage.csproj --configuration Release
    - name: Generate Swagger JSON
      run: |
        swagger tofile --output swagger.json src/FrontStage/bin/Release/net8.0/FrontStage.dll v1
    - name: Create Swagger UI
      run: |
        cat > index.html << EOL
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>RestaurantQueue API Documentation</title>
            <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/5.10.3/swagger-ui.min.css" />
            <script src="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/5.10.3/swagger-ui-bundle.min.js"></script>
        </head>
        <body>
            <div id="swagger-ui"></div>
            <script>
                window.onload = function() {
                  SwaggerUIBundle({
                    url: "swagger.json",
                    dom_id: '#swagger-ui',
                  })
                }
            </script>
        </body>
        </html>
        EOL
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        keep_files: false